<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyUvK19\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyUvK19/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSyUvK19.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSyUvK19\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSyUvK19\App_KernelDevDebugContainer([
    'container.build_hash' => 'SyUvK19',
    'container.build_id' => '5b6e4787',
    'container.build_time' => 1606040385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyUvK19');
