<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHU7DW99\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHU7DW99/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHU7DW99.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHU7DW99\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHU7DW99\App_KernelDevDebugContainer([
    'container.build_hash' => 'HU7DW99',
    'container.build_id' => 'c559a93c',
    'container.build_time' => 1606473453,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHU7DW99');
